		<ul class="nav nav-tabs nav-justified">
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		    <li role="presentation" class="active">
					<a href="!#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Usuarios</a></li>
		   	<li role="presentation">
				<div class="input-group">
					<input class="form-control" type="text" id="searchUsuario" placeholder="Buscar usuarios">
				</div></li>
				<li>
						&nbsp;<button type="button" class="btn btn-primary" title="Nuevo usuario" onclick="nuevoUsuario()">Nuevo Usuario</button>
	     </li>
			</ul></ul>
		  <!-- Tab panes -->
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active" id="detalle">
		    	<table class="table table-striped" id="tablaUsuario">
		    		<tr>
		    			<th>Id</th>
		    			<th>Nombres</th>
		    			<th>Apellidos</th>
		    			<th>Correo</th>
		    			<th>Telefono</th>
		    			<th>Nivel</th>
		    			<th>Opciones</th>
		    		</tr>
		    		<?php for($i=0; $i<count($usuarios); $i++){ $rs = $usuarios[$i]; ?>
		    		<tr>
		    			<td><?php echo $rs['id_usuario']; ?></td>
		    			<td><?php echo $rs['nombres']; ?></td>
		    			<td><?php echo $rs['apellidos']; ?></td>
		    			<td><?php echo $rs['correo']; ?></td>
		    			<td><?php echo $rs['telefono']; ?></td>
		    			<td><?php echo $rs['nivel']; ?></td>
		    			<td>
		    				<a href="#" onclick="editUsuario(this);" ><i class="glyphicon glyphicon-edit"></i></a>
		    				<a href="#" onclick="delUsuario(this);" ><i class="glyphicon glyphicon-trash"></i></a>
		    			</td>
		    		</tr><?php } ?>
		    	</table>
		    </div>
		  </div>