<?php 
    $ut = new Ut();
    $uts = $ut->getUt();
?>
<div class="modal fade" id="editGasto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar gasto</h4>
            </div>
            <div class="modal-body">
                <form id="formEditProveedor" action="../controllers/gastos/editGasto.php" method="post">
                    <div class="form-group">
                        <input class="form-control" type="hidden" name="new_id_gasto" id="new_id_gasto">
                    </div>
                    <div class="form-group">
                        <div class="form-group">
                            <select name="new_tipoGasto" id="new_tipoGasto" class="form-control">
                                <option value="">Selecciona un tipo</option>
                                <option value="1">Ordinario</option>
                                <option value="2">Alquiler</option>
                                <option value="3">Multa</option>                                
                            </select>
                         </div>
                    </div>
                    <div class="form-group">
                        <select name="new_id_utGasto" id="new_id_utGasto" class="form-control">
                            <option value="">Selecciona una unidad tributaria</option>
                            <?php for($i=0; $i<count($uts); $i++){ $rs = $uts[$i]; ?>
                                <option value="<?php echo $rs['id_ut']; ?>">
                                    <?php echo $rs['ut']; ?>        
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="new_numeroUts" id="new_numeroUts" placeholder="Número de UT's" autocomplete="off">
                    </div>                   
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_descripcion_gasto" id="new_descripcion_gasto" required placeholder="Descripcion" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_montoGasto" id="new_montoGasto" readonly="on" required placeholder="Monto" autocomplete="off">
                    </div>
                    
                    <!--<div class="form-group">
                        <input class="form-control" type="text" id="new_monto_gasto" onkeyup="subTotalGastoEdit(this);" placeholder="Monto" autocomplete="off">
                        <input type="hidden" name="new_monto_gasto" id="newTotalGasto">
                    </div>-->
                    
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>