		<ul class="nav nav-tabs nav-justified">
		  <!-- Nav tabs -->
		  <ul class="nav nav-tabs" role="tablist">
		    <li role="presentation" class="active"><a href="!#detalle" aria-controls="detalle" role="tab" data-toggle="tab">Documentos</a></li>
		 	
		 	<li role="presentation">
				<div class="input-group">
					<input class="form-control" type="text" id="searchDoc" placeholder="Buscar documentos">
				</div></li>  
				<li>		<?php if($_SESSION['nivel'] == 1 || $_SESSION['nivel'] == 2){ ?>			
						&nbsp;<button type="button" class="btn btn-primary" title="Nuevo Documento" onclick="nuevoDocumento()">Nuevo Documento</button>
	    					<?php } ?>
	    	</li>					
		  </ul></ul>
		  <!-- Tab panes -->
		  <div class="tab-content">
		    <div role="tabpanel" class="tab-pane active">
			    	
	    		<table class="table table-striped" id="tablaDoc">
		    		<tr>
		    			<th>Id</th>
		    			<th>Fecha</th>
		    			<th>Descripción / Descarga</th>
		    			<th>Opciones</th>
		    		</tr>
		    		<?php for($i=0; $i<count($documentos); $i++){ $rs = $documentos[$i]; ?>
		    		<tr>
		    			<td><?php echo $rs['id_documento']; ?></td>
		    			<td><?php echo $rs['fecha']; ?></td>
		    			<td><a href="../public/docs/<?php echo $rs['ubicacion']; ?>" target="_blank"><?php echo $rs['descripcion']; ?></a></td>
		    			<td>
		    				<?php if($_SESSION['idusuario'] == $rs['id_usuario']){ ?>
		    				<a href="#" onclick="editDocumento(this);" ><i class="glyphicon glyphicon-edit"></i></a>
		    				<a href="#" onclick="delDocumento(this, '<?php echo $rs['ubicacion']; ?>');" ><i class="glyphicon glyphicon-trash"></i></a>
		    				<?php } ?>
		    			</td>
		    		</tr> <?php } ?>
		    	</table>
		    </div>
		  </div>